### ISSUE TITLE
Admin access to NASA-JSC-Robotics

### ISSUE THREAD

**Issue by jsanchez19** [NASA-JSC-Robotics/robonaut2#1]
@wxmerkt @mamoll @bmagyar  can you please send me an e-mail to jairo.sanchez@nasa.gov. We realized there are no NASA members on this github organization and would like to have that resolved.

Thank you

**Comment by wxmerkt** [comment]
Hi @jsanchez19,
Neither of the three of us is an organisation owner and thus wouldn't be able to help resolve this. Here are the admins:
- @jasonduley 
- @jjholley 
- @nasa-valkyrie-robot
- @pstrawse
- @sonielau

Also happy to have a chat on the Valkyrie Slack or send an email if that works better.

Hope this helps, thanks,
Wolfgang

**Comment by jsanchez19** [comment]
odd, the only members listed on the organization page ([here](https://github.com/NASA-JSC-Robotics)) were you three. I'll get a hold of one of those folks. Thanks!

**Comment by bmagyar** [comment]
Github only shows those who set their memberships to public.
